---

- name: Users | Generate password
  set_fact:
    userPassword: "{{ lookup('password', '/dev/null chars=ascii_letters length=15') }}"

- name: Users | Generate salt encode
  set_fact:
    saltPassword: "{{ lookup('password', '/dev/null chars=ascii_letters length=15') }}"

- name: Users | Include OS variables
  include_vars: '{{ ansible_os_family }}.yml'

- name: Users | Include OS installation
  include_tasks: '{{ ansible_os_family }}.yml'
